### ISSUE TITLE
useless repo

### ISSUE THREAD

**Issue by 3S0** [ProfKambing/Esohack-burrow#1]
https://github.com/ciruu1/InstantBurrow

note: i didn't obfuscate anything in esohack, please stop spreading misinformation.

**Comment by ProfKambing** [comment]
wwhy did you skid burrow 😐

**Comment by 3S0** [comment]
why are you reposting skidded burrow😐

**Comment by ProfKambing** [comment]
phobos-ported burrow 😉

**Comment by 3S0** [comment]
all you have to do is change imports... nothing special needed to "port" it to phobos from original source
